### PR TITLE
feat:404 page added

### PR DESCRIPTION
**Pull request by Thoughtscript**
Opening this now but still verifying styles and testing a few things.

Will also be moving some of the presentation components properly into the `presentation`.

Per: https://github.com/kleros/arbitrable-payment-front/projects/1

Will screen shot when done 😄

### CODE REVIEW

**Comment by n1c01a5** [comment]
the "skeleton" for all kleros front is `kleros/dapper`. 404 feature is already implemented on dapper see https://github.com/kleros/dapper/commit/a7f3d78d7c3bfe853cf3e309b83cf87f59d609a3 . Can you implement this issue or change the 404 workflow on dapper

**Comment by Thoughtscript** [comment]
Ah sure, I will make a few small modifications to bring it up to Dapper spec:

capture

Thanks!

**Comment by Thoughtscript** [comment]
@n1c01a5:

1. I renamed the component per Dapper spec
2. Altered the route in Switch per Dapper spec
3. Altered the class styling convention per Dapper spec

It's the underlying Page-Not-Found component with the basic styling for the app in the header and footer. Please let me know if there are other changes I can make. Cheers!

**Comment by n1c01a5** [comment]
The deploy failed on netlify

**Comment by Thoughtscript** [comment]
Fixed - import path changed after I moved the `footers` into the `presentation components` path. I thought that'd be more sensible. Please let me know if there are any other items that can be improved here.

Linting and error related changes from the `precommit` process have been improved in another PR: https://github.com/kleros/arbitrable-payment-front/pull/31

**Comment by n1c01a5** [comment]
@Thoughtscript thx I added your bounty on https://docs.google.com/spreadsheets/d/1Cn9DEamADHcBT_VFWtb0ot2KY4j8A1ud6xFNfDnsjjM/edit#gid=335269204

**Pull request merged**
